### ISSUE TITLE
concurrent lib有个地方锁没释放

### ISSUE THREAD

**Issue by Pengfei00** [beinan/gql-server#1]
concurrent/cache/cache.go:34
这里直接返回了没释放锁哦

**Comment by beinan** [comment]
不好意思不好意思，才看到这个issue。真的是非常感谢，我这就修改。感谢🙏

**Comment by beinan** [comment]
https://github.com/beinan/gql-server/commit/dff417c929a87ef45f312df10e5a2c36d8d05714
